import { Building2 } from 'lucide-react'

export const mockData = [
  {
    id: 1,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-926",
    measurement: "1,245 kWh",
    tonsOfCO2e: 0.45,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "John Smith",
    tags: "Electricity, Monthly",
    cost: 156.78,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 2,
    site: "NYC HQ",
    description: "Natural Gas Usage",
    measurement: "450 therms",
    tonsOfCO2e: 2.39,
    startDate: "2025-02-01",
    endDate: "2025-03-01",
    status: "Healthy Data",
    assignedTo: "Sarah Chen",
    tags: "Gas, Heating",
    cost: 678.50,
    scope: "Scope 1",
    organization: "Acme Corp"
  },
  {
    id: 3,
    site: "Austin Campus",
    description: "Solar Panel Generation",
    measurement: "22,450 kWh",
    tonsOfCO2e: -4.12,
    startDate: "2025-01-15",
    endDate: "2025-02-15",
    status: "Pending Gravity QA",
    assignedTo: "Mike Johnson",
    tags: "Renewable, Generation",
    cost: null,
    scope: "Scope 2",
    organization: "TechStart Inc"
  },
  {
    id: 4,
    site: "London Office",
    description: "Business Travel - Flights",
    measurement: "12,500 miles",
    tonsOfCO2e: 3.85,
    startDate: "2024-12-01",
    endDate: "2024-12-31",
    status: "Needs Review",
    assignedTo: "Emma Wilson",
    tags: "Travel, Air",
    cost: 4500.00,
    scope: "Scope 3",
    organization: "Global Dynamics"
  },
  {
    id: 5,
    site: "Chicago Warehouse",
    description: "Fleet Vehicles - Diesel",
    measurement: "850 gallons",
    tonsOfCO2e: 8.67,
    startDate: "2025-01-01",
    endDate: "2025-01-31",
    status: "Healthy Data",
    assignedTo: "Robert Lee",
    tags: "Transport, Fleet",
    cost: 3245.75,
    scope: "Scope 1",
    organization: "Logistics Plus"
  },
  {
    id: 6,
    site: "Mumbai Center",
    description: "Water Consumption",
    measurement: "125,000 gallons",
    tonsOfCO2e: 0.89,
    startDate: "2025-02-01",
    endDate: "2025-02-28",
    status: "Pending Gravity QA",
    assignedTo: "Priya Patel",
    tags: "Water, Utility",
    cost: 875.25,
    scope: "Scope 3",
    organization: "TechStart Inc"
  },
  {
    id: 7,
    site: "Berlin Office",
    description: "Purchased Equipment",
    measurement: "",
    tonsOfCO2e: 12.45,
    startDate: "2025-01-15",
    endDate: "2025-01-15",
    status: "Needs Review",
    assignedTo: "Hans Mueller",
    tags: "Capital Goods",
    cost: 24500.00,
    scope: "Scope 3",
    organization: "Euro Tech GmbH"
  },
  {
    id: 8,
    site: "Sydney HQ",
    description: "Waste Management",
    measurement: "2.5 tons",
    tonsOfCO2e: 1.23,
    startDate: "2025-01-01",
    endDate: "2025-01-31",
    status: "Healthy Data",
    assignedTo: "James Wilson",
    tags: "Waste, Monthly",
    cost: 450.00,
    scope: "Scope 3",
    organization: "Pacific Solutions"
  },
  {
    id: 9,
    site: "Toronto Office",
    description: "Employee Commuting",
    measurement: "45,000 miles",
    tonsOfCO2e: 16.78,
    startDate: "2024-12-01",
    endDate: "2024-12-31",
    status: "Pending Gravity QA",
    assignedTo: "Marie Dubois",
    tags: "Transport, Commute",
    cost: null,
    scope: "Scope 3",
    organization: "Northern Industries"
  },
  {
    id: 10,
    site: "SF Office",
    description: "Refrigerant Leakage",
    measurement: "5 kg",
    tonsOfCO2e: 9.45,
    startDate: "2025-02-01",
    endDate: "2025-02-01",
    status: "Needs Review",
    assignedTo: "David Kim",
    tags: "Refrigerants, Maintenance",
    cost: 750.00,
    scope: "Scope 1",
    organization: "Vandelay Industries"
  },
  {
    id: 11,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-925",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 12,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-924",
    measurement: "650 kWh",
    tonsOfCO2e: 0.13,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 13,
    site: "SF Office",
    description: "Scanned Bill, meter 001-700-033",
    measurement: "13,489 kWh",
    tonsOfCO2e: 2.68,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 14,
    site: "SF Office",
    description: "CNC-TOOLHOLDERS & ATTACHMENTS",
    measurement: "",
    tonsOfCO2e: 36.00,
    startDate: "2023-12-24",
    endDate: "2023-12-24",
    status: "Healthy Data",
    assignedTo: "-",
    tags: "",
    cost: 174247,
    scope: "Scope 3",
    organization: "Vandelay Industries"
  },
  {
    id: 15,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-926",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 16,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-925",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 17,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-924",
    measurement: "650 kWh",
    tonsOfCO2e: 0.13,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 18,
    site: "SF Office",
    description: "Scanned Bill, meter 001-700-033",
    measurement: "13,489 kWh",
    tonsOfCO2e: 2.68,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 19,
    site: "SF Office",
    description: "CNC-TOOLHOLDERS & ATTACHMENTS",
    measurement: "",
    tonsOfCO2e: 36.00,
    startDate: "2023-12-24",
    endDate: "2023-12-24",
    status: "Healthy Data",
    assignedTo: "-",
    tags: "",
    cost: 174247,
    scope: "Scope 3",
    organization: "Vandelay Industries"
  },
  {
    id: 20,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-926",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 21,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-925",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 22,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-924",
    measurement: "650 kWh",
    tonsOfCO2e: 0.13,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 23,
    site: "SF Office",
    description: "Scanned Bill, meter 001-700-033",
    measurement: "13,489 kWh",
    tonsOfCO2e: 2.68,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 24,
    site: "SF Office",
    description: "CNC-TOOLHOLDERS & ATTACHMENTS",
    measurement: "",
    tonsOfCO2e: 36.00,
    startDate: "2023-12-24",
    endDate: "2023-12-24",
    status: "Healthy Data",
    assignedTo: "-",
    tags: "",
    cost: 174247,
    scope: "Scope 3",
    organization: "Vandelay Industries"
  },
  {
    id: 25,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-926",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 26,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-925",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 27,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-924",
    measurement: "650 kWh",
    tonsOfCO2e: 0.13,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 28,
    site: "SF Office",
    description: "Scanned Bill, meter 001-700-033",
    measurement: "13,489 kWh",
    tonsOfCO2e: 2.68,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 29,
    site: "SF Office",
    description: "CNC-TOOLHOLDERS & ATTACHMENTS",
    measurement: "",
    tonsOfCO2e: 36.00,
    startDate: "2023-12-24",
    endDate: "2023-12-24",
    status: "Healthy Data",
    assignedTo: "-",
    tags: "",
    cost: 174247,
    scope: "Scope 3",
    organization: "Vandelay Industries"
  },
  {
    id: 30,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-926",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 31,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-925",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 32,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-924",
    measurement: "650 kWh",
    tonsOfCO2e: 0.13,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 33,
    site: "SF Office",
    description: "Scanned Bill, meter 001-700-033",
    measurement: "13,489 kWh",
    tonsOfCO2e: 2.68,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 34,
    site: "SF Office",
    description: "CNC-TOOLHOLDERS & ATTACHMENTS",
    measurement: "",
    tonsOfCO2e: 36.00,
    startDate: "2023-12-24",
    endDate: "2023-12-24",
    status: "Healthy Data",
    assignedTo: "-",
    tags: "",
    cost: 174247,
    scope: "Scope 3",
    organization: "Vandelay Industries"
  },
  {
    id: 35,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-926",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 36,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-925",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 37,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-924",
    measurement: "650 kWh",
    tonsOfCO2e: 0.13,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 38,
    site: "SF Office",
    description: "Scanned Bill, meter 001-700-033",
    measurement: "13,489 kWh",
    tonsOfCO2e: 2.68,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 39,
    site: "SF Office",
    description: "CNC-TOOLHOLDERS & ATTACHMENTS",
    measurement: "",
    tonsOfCO2e: 36.00,
    startDate: "2023-12-24",
    endDate: "2023-12-24",
    status: "Healthy Data",
    assignedTo: "-",
    tags: "",
    cost: 174247,
    scope: "Scope 3",
    organization: "Vandelay Industries"
  },
  {
    id: 40,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-926",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 41,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-925",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 42,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-924",
    measurement: "650 kWh",
    tonsOfCO2e: 0.13,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 43,
    site: "SF Office",
    description: "Scanned Bill, meter 001-700-033",
    measurement: "13,489 kWh",
    tonsOfCO2e: 2.68,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 44,
    site: "SF Office",
    description: "CNC-TOOLHOLDERS & ATTACHMENTS",
    measurement: "",
    tonsOfCO2e: 36.00,
    startDate: "2023-12-24",
    endDate: "2023-12-24",
    status: "Healthy Data",
    assignedTo: "-",
    tags: "",
    cost: 174247,
    scope: "Scope 3",
    organization: "Vandelay Industries"
  },
  {
    id: 45,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-926",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 46,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-925",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 47,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-924",
    measurement: "650 kWh",
    tonsOfCO2e: 0.13,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 48,
    site: "SF Office",
    description: "Scanned Bill, meter 001-700-033",
    measurement: "13,489 kWh",
    tonsOfCO2e: 2.68,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 49,
    site: "SF Office",
    description: "CNC-TOOLHOLDERS & ATTACHMENTS",
    measurement: "",
    tonsOfCO2e: 36.00,
    startDate: "2023-12-24",
    endDate: "2023-12-24",
    status: "Healthy Data",
    assignedTo: "-",
    tags: "",
    cost: 174247,
    scope: "Scope 3",
    organization: "Vandelay Industries"
  },
  {
    id: 50,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-926",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 51,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-925",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 52,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-924",
    measurement: "650 kWh",
    tonsOfCO2e: 0.13,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 53,
    site: "SF Office",
    description: "Scanned Bill, meter 001-700-033",
    measurement: "13,489 kWh",
    tonsOfCO2e: 2.68,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 54,
    site: "SF Office",
    description: "CNC-TOOLHOLDERS & ATTACHMENTS",
    measurement: "",
    tonsOfCO2e: 36.00,
    startDate: "2023-12-24",
    endDate: "2023-12-24",
    status: "Healthy Data",
    assignedTo: "-",
    tags: "",
    cost: 174247,
    scope: "Scope 3",
    organization: "Vandelay Industries"
  },
  {
    id: 55,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-926",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 56,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-925",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 57,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-924",
    measurement: "650 kWh",
    tonsOfCO2e: 0.13,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 58,
    site: "SF Office",
    description: "Scanned Bill, meter 001-700-033",
    measurement: "13,489 kWh",
    tonsOfCO2e: 2.68,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 59,
    site: "SF Office",
    description: "CNC-TOOLHOLDERS & ATTACHMENTS",
    measurement: "",
    tonsOfCO2e: 36.00,
    startDate: "2023-12-24",
    endDate: "2023-12-24",
    status: "Healthy Data",
    assignedTo: "-",
    tags: "",
    cost: 174247,
    scope: "Scope 3",
    organization: "Vandelay Industries"
  },
  {
    id: 60,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-926",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 61,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-925",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 62,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-924",
    measurement: "650 kWh",
    tonsOfCO2e: 0.13,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 63,
    site: "SF Office",
    description: "Scanned Bill, meter 001-700-033",
    measurement: "13,489 kWh",
    tonsOfCO2e: 2.68,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 64,
    site: "SF Office",
    description: "CNC-TOOLHOLDERS & ATTACHMENTS",
    measurement: "",
    tonsOfCO2e: 36.00,
    startDate: "2023-12-24",
    endDate: "2023-12-24",
    status: "Healthy Data",
    assignedTo: "-",
    tags: "",
    cost: 174247,
    scope: "Scope 3",
    organization: "Vandelay Industries"
  },
  {
    id: 65,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-926",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 66,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-925",
    measurement: "0 kWh",
    tonsOfCO2e: 0.00,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 67,
    site: "SF Office",
    description: "Scanned Bill, meter 002-068-924",
    measurement: "650 kWh",
    tonsOfCO2e: 0.13,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 68,
    site: "SF Office",
    description: "Scanned Bill, meter 001-700-033",
    measurement: "13,489 kWh",
    tonsOfCO2e: 2.68,
    startDate: "2025-01-22",
    endDate: "2025-02-22",
    status: "Pending Gravity QA",
    assignedTo: "-",
    tags: "",
    cost: null,
    scope: "Scope 2",
    organization: "Vandelay Industries"
  },
  {
    id: 69,
    site: "SF Office",
    description: "CNC-TOOLHOLDERS & ATTACHMENTS",
    measurement: "",
    tonsOfCO2e: 36.00,
    startDate: "2023-12-24",
    endDate: "2023-12-24",
    status: "Healthy Data",
    assignedTo: "-",
    tags: "",
    cost: 174247,
    scope: "Scope 3",
    organization: "Vandelay Industries"
  }
]

// Column definitions for the table
export const columns = [
    {
        header: "Site",
        accessorKey: "site",
        cell: ({ getValue }) => (
          <div className="flex items-center gap-2">
            <Building2 className="h-4 w-4 text-gray-500 stroke-[1.5]" />
            <span className="font-semibold">
              {getValue()}
            </span>
          </div>
        ),
    },
    {
        header: "Scope",
        accessorKey: "scope",
    },
    {
        header: "Organization",
        accessorKey: "organization",
    },
    {
        header: "Description",
        accessorKey: "description",
    },
    {
        header: "Measurement",
        accessorKey: "measurement",
        cell: ({ getValue }) => {
          const value = getValue()
          if (!value) return ""
          const [number, unit] = value.split(" ")
          return (
            <div className="flex justify-between items-center">
              <span className="text-gray-500">{unit}</span>
              <span className="font-medium">{number}</span>
            </div>
          )
        },
    },
    {
        header: "Tons of CO2e",
        accessorKey: "tonsOfCO2e",
        cell: ({ getValue }) => {
          const value = getValue()
          return (
            <div className="text-right">
              <span className="font-medium">{value.toFixed(2)}</span>
            </div>
          )
        },
    },
    {
        header: "Start Date",
        accessorKey: "startDate",
        cell: ({ getValue }) => {
          const date = new Date(getValue())
          return `${date.getDate()} ${date.toLocaleString('en-US', { month: 'short' })} ${date.getFullYear()}`
        },
    },
    {
        header: "End Date",
        accessorKey: "endDate",
        cell: ({ getValue }) => {
          const date = new Date(getValue())
          return `${date.getDate()} ${date.toLocaleString('en-US', { month: 'short' })} ${date.getFullYear()}`
        },
    },
    {
        header: "Status",
        accessorKey: "status",
        cell: ({ getValue }) => {
          const status = getValue()
          const getStatusStyles = (status) => {
            switch (status) {
              case 'Pending Gravity QA':
                return 'bg-sky-50 text-sky-700 border-sky-100'
              case 'Healthy Data':
                return 'bg-emerald-50 text-emerald-700 border-emerald-100'
              default:
                return 'bg-gray-50 text-gray-700 border-gray-100'
            }
          }

          return (
            <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${getStatusStyles(status)}`}>
              {status}
            </span>
          )
        },
    },
    {
        header: "Assigned To",
        accessorKey: "assignedTo",
    },
    {
        header: "Tags",
        accessorKey: "tags",
    },
    {
        header: "Cost",
        accessorKey: "cost",
        cell: ({ getValue }) => {
          const value = getValue()
          if (value === null) return "-"
          return (
            <div className="flex justify-between items-center">
              <span className="text-gray-500">$</span>
              <span className="font-medium">{value.toLocaleString()}</span>
            </div>
          )
        },
    }
]
